### ISSUE TITLE
Phase 2 : Text styling ไม่เหมือนกันใน 1 หน้า

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#100]
Styling น่าจะติดมาจากการ Copy Text มาจากWord  เวลาเอาText มาลงรบกวนล้าง Style ที่ติดมาด้วยให้หน่อยได้ไหมคะ

Link:
https://dev-blockfint.vercel.app/blog/firstblog
Image : 
![image](https://user-images.githubusercontent.com/82858380/120253881-c5986c00-c2b2-11eb-93c7-6365d602ab73.png)

**Comment by jakapatb** [comment]
ซ้ำ #96 #99
