### ISSUE TITLE
Work : ปุ่ม see more ลืมเปลี่ยนเป็นภาษาไทย

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#110]
https://dev-blockfint.vercel.app/th/works
ปุ่ม see more
ฝั่งภาษาไทย แก้เป็นคำว่า อ่านเพิ่มเติม เหมือนด้านล่างค่ะ

![image](https://user-images.githubusercontent.com/82858380/122503861-5eedaf00-d023-11eb-8d6a-46aaa262dcf8.png)

**Comment by jakapatb** [comment]
https://dev-blockfint.vercel.app/works

**Comment by momoparadise** [comment]
![Uploading image.png…]()
