### ISSUE TITLE
รูปเปลี่ยน svg Thinker LOS ที่หน้าถูกบีบ

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#116]
ขอเปลี่ยนรูปมาใช้ไฟล์ pngแทน รูปนี้ อยู่ในDriveด้านล่างนี้
https://drive.google.com/drive/folders/1DbikqqW_AJiPdyrRD9n1wpRJqJd-RhB_?usp=sharing

เราExportมาเป็น svg มาจากFigma แล้วภาพถูกบีบมาเป็นแบบนี้ แก้ไงก็ไม่หาย
![image](https://user-images.githubusercontent.com/74232630/123187992-77e3dd80-d4c5-11eb-98db-7bd96cc7ebef.png)

จริงๆภาพต้องเป็นแบบนี้
![image](https://user-images.githubusercontent.com/74232630/123188092-9e097d80-d4c5-11eb-9a96-4eb907ec0d06.png)

**Comment by jakapatb** [comment]
https://dev-blockfint.vercel.app/works
