### ISSUE TITLE
กด thumbnail 'Thinker wise' แล้วลิงค์ไปผิดหน้า

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#117]
ในหน้าWork เมื่อกด thumbnail 'Thinker wise' แล้วตอนนี้ลิงค์ไปที่ Thinker LOS detail

ที่ถูก
กดThinker wise ในหน้า Work แล้วต้องไปเจอหน้า Thinker wise detail ตามZeplinด้านล่าง
zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=60c6dc5252129c1331016ccb

รูปภาพเอาได้ในDriveนี้
https://drive.google.com/drive/folders/1hW01su904gMEA7b7kVwpbmaMVeeVDqXW?usp=sharing

**Comment by jakapatb** [comment]
https://dev-blockfint.vercel.app/works

**Comment by Phunut** [comment]
@jakapatb ภาพ Thinker wise ในหน้าDetail โดนบีบน่ะค่ะ ตรงวงกลมมันไม่กลม 
https://dev-blockfint.vercel.app/products/thinker-wise

**Comment by jakapatb** [comment]
@jakapatb fixed
https://dev-blockfint.vercel.app/works
