### ISSUE TITLE
เพิ่มสมาชิก หน้าTeam&Team detail

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#123]
เพิ่มสมาชิก หน้าTeam&Team detail
- [x] หน้าTeam จะมีสมาชิกเพิ่มมาอีก3คน (Natnicha, Nisita, Phathsinee)
- [x] หน้าDetail ของสมาชิกที่เพิ่มมาใหม่ทั้ง 3 คน
- [x] เปลี่ยนชื่อตำแหน่งพี่ โอ๊ค พี่เอก ให้เป็นชื่อเต็ม

Zeplin
หน้าTeam: zpl://screen?sid=5f8e709f29bb6387e6c8b86c&pid=5f8d42f6c140c35b10d56a7c
หน้าTeam detail: zpl://screen?sid=5f8e709483134f89289359f1&pid=5f8d42f6c140c35b10d56a7c

รูป: https://drive.google.com/drive/folders/1WXDuE_9Gd9oJI7QBjJQl14Dbnph9dim1?usp=sharing

content: https://docs.google.com/spreadsheets/d/1nKvK2A723Lw_U6CgQ31_yN0kLd4BEEAwOPd4NyQtg1Y/edit#gid=2031554464

**Comment by jakapatb** [comment]
- [ ] ขาดหน้า Phathsinee

**Comment by Phunut** [comment]
- [ ] รูปPhasiness มาแล้วนะคะ  https://drive.google.com/drive/folders/1WXDuE_9Gd9oJI7QBjJQl14Dbnph9dim1?usp=sharing
- [ ] ใส่หน้าประวัติBio ของพี่มะเหมี่ยวได้เลย Contentมาแล้วค่ะhttps://docs.google.com/spreadsheets/d/1nKvK2A723Lw_U6CgQ31_yN0kLd4BEEAwOPd4NyQtg1Y/edit#gid=2031554464

**Comment by momoparadise** [comment]
![image](https://user-images.githubusercontent.com/82858380/137784638-2ecae9a2-db4e-4440-a3c2-a3e217f41df8.png)


> * [x]  รูปPhasiness มาแล้วนะคะ  https://drive.google.com/drive/folders/1WXDuE_9Gd9oJI7QBjJQl14Dbnph9dim1?usp=sharing

![image](https://user-images.githubusercontent.com/82858380/137784648-e7431a83-d9ed-4b78-a1bd-325b15ffb749.png)



> * [x]  ใส่หน้าประวัติBio ของพี่มะเหมี่ยวได้เลย Contentมาแล้วค่ะhttps://docs.google.com/spreadsheets/d/1nKvK2A723Lw_U6CgQ31_yN0kLd4BEEAwOPd4NyQtg1Y/edit#gid=2031554464

![image](https://user-images.githubusercontent.com/82858380/137784829-9e260ef1-0fcc-4def-820d-4fbec29660ec.png)
