### ISSUE TITLE
ขนาดภาพไม่เปลี่ยนไปตามหน้าจอ responsive

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#126]
เวลาลดขนาดหน้าจอลงแล้วตรงรูปจะมีสีเทาขึ้นแบบนี้น่ะฮะ
![image](https://user-images.githubusercontent.com/74232630/132613674-dccc9a67-29d5-4b60-9112-587319b70399.png)

**Comment by Phunut** [comment]
@thanakrit07  
ที่เชคล่าสุดคือ
-ถ้าดูจากDesktop ไม่โดนครอปไม่มีเส้นเทา คิดว่าโอเคแล้วค่ะ
-ถ้าดูจากipad จะไม่โดนCrop แต่จะมีเส้นเทาๆขึ้นแบบนี้

 ![IMG_4DF0E20DF5CD-1](https://user-images.githubusercontent.com/74232630/138210763-98ffc7d4-f575-43a7-97ce-35015706f7a1.jpeg)

**Comment by Phunut** [comment]
- [ ]  หน้าจอiphone  6 ภาพมีขีดๆแบบนี้ค่ะ ฝากแก้ด้วย @thanakrit07 
![CBFAA9E1-C191-4B7D-908C-67DD03B83FDB](https://user-images.githubusercontent.com/74232630/140016726-20d35b4b-f1c7-4bc5-b0a8-be92030b3e2c.jpg)

**Comment by thanakrit07** [comment]
https://blockfint-landing-2020-git-develop-blockfint.vercel.app อันนี้ล่าสุด ฝากเช็คหน่อยคับพี่ @Phunut
