### ISSUE TITLE
launch หน้าBlogs/ หน้าTag /หน้าContributor  ได้เลยค่ะ

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#127]
launch หน้าที่เคยทำกันไว้แต่ตอนนี้Hideไว้อยู่ได้เลยค่ะ มีทั้งหมด3หน้า

- [x] หน้าBlogs   zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=613743a1dec3922f03b21251
- [x] หน้าTag   zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=613743af04960e432a65728f
- [x] หน้าContributor   zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=613743b391b72d43d0fb7e8a

ตอนนี้บทความเรามีมากขึ้นพอที่จะแสดงที่หน้าเหล่านั้นได้แล้วค่ะ. เรากำลังทะยอยอัพบทความขึ้นไปนะ มีประมาณ 6 บทความ

**Comment by momoparadise** [comment]
ใน demo มีหมดแล้ว
https://blockfint-landing-2020-git-feature-vc-project-blockfint.vercel.app/th/blog

เหลือเอาขึ้น https://www.blockfint.com/ ค่ะ

@jakapatb
