### ISSUE TITLE
ถ้ากด tag  #ESOP จากหน้าDetail ในหน้าtagมันควรขึ้นเป็นคำว่า #ESOP ด้วย ตอนนี้มันขึ้นคำว่า#Hash-esop

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#128]
- [x]  หน้านี้ตรงชื่อ ถ้ากด tag  #ESOP ในหน้าtagมันควรขึ้นเป็นคำว่า #ESOPด้วย ตอนนี้มันขึ้นคำว่า#Hash-esopค่า
https://blockfint-landing-2020-git-feature-vc-project-blockfint.vercel.app/blog/tag/hash-esop
![image](https://user-images.githubusercontent.com/74232630/136881781-4bd9ccfc-b461-421f-ac7b-4a6f43121e6f.png)

**Comment by Phunut** [comment]
@thanakrit07  มันยังคงชื่อ hastag ไม่ตรงอยู่เลยอะ 
![image](https://user-images.githubusercontent.com/74232630/141738028-c6f2599c-cffa-40a7-9f16-a81bdbd9cabe.png)

**Comment by thanakrit07** [comment]
![Screen Shot 2564-11-23 at 12 02 10](https://user-images.githubusercontent.com/31263127/142973911-dd9cfae5-b07b-4885-8c70-279ba2f9b15f.png
![Screen Shot 2564-11-23 at 12 04 13](https://user-images.githubusercontent.com/31263127/142973916-a60ede0b-373f-41ec-a24b-39d7ddf88748.png)
)

@Phunut 
- เวลาสร้าง tag ใหม่ทุกครั้ง จะต้องมาที่หัวข้อ tags (1) กดไปที่ internal tags (มุมบนขวา ข้างซ้ายปุ่ม new tag)
- จากนั้นแก้ชื่อ slug (2, 3) ให้ตรงกับที่จะ show บน web (ใน slug ไม่ต้องมี #) 
- กด save (4)

เพิ่มเติม : slug ของ internal tags กับ public tags (ใน web คือ category) จะซ้ำกันไม่ได้ 
จะเห็นว่าจะมี internal tags บางอันที่ชื่อเหมือน public tags (เช่น blockchain ) slug ของ ตัวนั้นเลยเป็น blockchain-2

**Comment by Phunut** [comment]
@thanakrit07    ตอนนี้เมื่อสร้างTag ที่เป็นภาษาไทย เช่น#การเงิน >>เมื่อกดเข้าไปที่Tagนั้นๆ มันจะกลายเป็นภาษาคาราโอเกะ> #Kaarengin
![image](https://user-images.githubusercontent.com/74232630/144158104-d8e69ec8-27a4-4efc-9a22-73d35b3068c0.png)
![image](https://user-images.githubusercontent.com/74232630/144158127-202854c9-a316-443d-be8b-8b1a37d28b30.png)
