### ISSUE TITLE
เติมชื่อตำแหน่งพี่มะเหมี่ยว

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#131]
ตำแหน่งพี่มะเหมี่ยวยังเป็น required  >> https://blockfint-landing-2020-git-feature-vc-project-blockfint.vercel.app/team
ให้แก้เป็นชื่อตำแหน่งเป็นตามนี้ค่ะ

- [x] TH - ผู้จัดการและวางแผนการออกแบบ
- [x] EN - UX/UI Manager

![image](https://user-images.githubusercontent.com/74232630/136888338-66fa6471-6141-4ea4-8909-5342b90e6e29.png)

**Comment by momoparadise** [comment]
![image](https://user-images.githubusercontent.com/82858380/137717663-06da8ada-ae9e-4647-95a5-9b264d22b2f8.png)
Done
