### ISSUE TITLE
[หน้าBlog] จะแสดงเฉพาะCateที่มีบทความเท่านั้น  Cateที่ยังไม่มีบทความจะไม่แสดงให้เห็น

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#133]
ตอนนี้บทความี Category  Financial และBlockchain
หน้าจอก็ควรโชว์แค่. All , financial , Blockchain (จะแสดงเฉพาะCateที่มีบทความเท่านั้น  Cateที่ยังไม่มีบทความจะไม่แสดงให้เห็น)

![image](https://user-images.githubusercontent.com/74232630/136939349-fc9ee6a3-5d21-46e8-9308-d03945bcb317.png)

**Comment by momoparadise** [comment]
ตอนนี้ยังแสดง Category ที่ไม่มีบทความอยู่ค่ะ
![image](https://user-images.githubusercontent.com/82858380/137785061-24e1a097-ba1f-4383-ad5b-0e06c661c80e.png)
