### ISSUE TITLE
พื้นหลังขาดรูปกล่องค่ะ

### ISSUE THREAD

**Issue by metpiya** [blockfint/blockfint-landing-2020#141]
ภาพพื้นหลังที่เป็นรูปกล่องหาย  

![S__48144404](https://user-images.githubusercontent.com/93700351/140454498-def9d3a5-6bed-412f-b086-ba26363c5cbe.jpg)

- [x] จริงๆต้องเป็นแบบนี้ค่ะ zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=613743e55c5cc730180267f9
<img width="375" alt="ภาพถ่ายหน้าจอ 2564-11-05 เวลา 10 43 27" src="https://user-images.githubusercontent.com/93700351/140454793-c453fb2a-3082-4683-8dd3-f85409d8c38e.png">

**Comment by Phunut** [comment]
@thanakrit07  https://drive.google.com/drive/folders/12UQZrjX3P16PI0Xrt9YjTWOt0nBcf6NM?usp=sharing รูปBGที่ต้องใส่ลงไปค่ะ
