### ISSUE TITLE
ตรง hamberger ตรงเปลี่ยนภาษากับ follower ซ้อนกัน

### ISSUE THREAD

**Issue by metpiya** [blockfint/blockfint-landing-2020#146]
ซ้อนกันแบบนี้ค่ะ มันทับกันอยู่
![image](https://user-images.githubusercontent.com/93700351/140484115-82acb3bb-279c-4921-87c0-92ec34ada815.png)

- [ ] รบกวนปรับให้ไม่ทับกันหน่อยค่ะ

**Comment by Phunut** [comment]
@thanakrit07   ไม่ต้องFix Social media ให้ติดกับด้านล่างแล้ว
เอาเป็น Design ตามนี้แล้วก็ให้ scroll เลื่อนได้ >> zpl://screen?sid=5f8e8667c7d3b352a5ec0310&pid=5f8d42f6c140c35b10d56a7c
