### ISSUE TITLE
เพิ่มการใส่Code, Bullet point และ Break line 

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#150]
หน้าBlog detailตอนนี้ถ้าอยากใส่ Code, Bullet point , Break line 
ตามใน >> zpl://screen?sid=6164fe808f67e717b2ba13c7&pid=5f8d42f6c140c35b10d56a7c
ตอนนี้ในหน้าCMS ยังไม่มีให้ใส่ค่ะ หรือถ้ามันใส่ได้อยุ่แล้วรบกวนคอมเม้นบอกทีค่ะว่าต้องกดตรงไหน พอดีหาไม่เจอน่ะคะ

**Comment by thanakrit07** [comment]
<img width="745" alt="Screen Shot 2564-11-26 at 16 13 31" src="https://user-images.githubusercontent.com/31263127/143556391-47c65fab-976d-46e3-82a4-4f588c74b5f8.png">

ตัว Quote ถ้าพิมปกติจะเป็นตัวสีเทาเล็กแบบด้านล่าง แต่ถ้าจะให้เป็นตัวสีดำใหญ่ ต้องทำให้เป็นตัวหนา ( B: bold text)

**Comment by Phunut** [comment]
@thanakrit07  
อันนี้เราลองเลือก "โลก Metaverse เคยถูกนำไปใช้อย่างในภาพยนตร์เรื่อง Ready Player One ที่มีการเข้าไปเล่นเกม ซื้อขายแลกเปลี่ยนสิ่งของ ในสถานที่ต่าง ๆ  ทำให้เราเริ่มเห็นภาพจินตนาการของ Metaverse ได้ชัดเจนขึ้น" เป็น Quote นะ. น้องยังเป็นตัวจิ๋วๆอยู่เลย ไม่เหมือนในดีไซน์อ่า


![image](https://user-images.githubusercontent.com/74232630/145982163-9037b7cc-d108-410a-a80a-1e6485564c39.png)
