### ISSUE TITLE
แก้Quoteที่ตอนนี้เป็นตัวอักษรกลายเป็นตัวจิ๋วๆ  ให้เป็นแบบที่ถูกต้อง

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#152]
ตรงQuote ที่ถูกต้องต้องเป็นแบบนี้ค่ะ
![image](https://user-images.githubusercontent.com/74232630/141751762-a1871aea-8a25-477a-9c3e-d2a27913205e.png)

แต่ตอนนี้ในBF.com กลายเป็นตัวจิ๋วๆแบบนี้
![image](https://user-images.githubusercontent.com/74232630/141751976-e63f6f74-32b2-4e35-a0be-88ad90f66b04.png)

ในCMS เป็นแบบนี้
![image](https://user-images.githubusercontent.com/74232630/141752061-b566acfe-f8ad-4e9b-b761-bf1cee25bc23.png)

**Comment by thanakrit07** [comment]
ตามใน #150

**Comment by Phunut** [comment]
@thanakrit07
อันนี้เราลองเลือกประโยคนี้ เป็น Quote นะ>> "โลก Metaverse เคยถูกนำไปใช้อย่างในภาพยนตร์เรื่อง Ready Player One ที่มีการเข้าไปเล่นเกม ซื้อขายแลกเปลี่ยนสิ่งของ ในสถานที่ต่าง ๆ ทำให้เราเริ่มเห็นภาพจินตนาการของ Metaverse ได้ชัดเจนขึ้น".  แต่น้องยังเป็นตัวจิ๋วๆอยู่เลย ไม่เหมือนในดีไซน์อ่า

![image](https://user-images.githubusercontent.com/74232630/145982626-2fccc7c7-7497-43fe-82d9-ef007307e26c.png)

**Comment by Phunut** [comment]
ตัวหนังสือ ตรงquote  @thanakrit07 
- มีเส้นข้างหน้าแบบที่กายทำมาถุกแล้วค่ะ
- [ ] - เราขอปรับเป็นตัวหนังสือตรงนี้ที่ปัจจุบันเป็นสีเทา ให้เป็นสีดำ และใหญ่ขึ้นเป็น 20px ค่ะ

แบบนี้ค่ะ
![image](https://user-images.githubusercontent.com/74232630/147462646-e967897d-6f3f-435d-a249-8b6dce700c98.png)


ปัจจุบัน
![image](https://user-images.githubusercontent.com/74232630/147462692-acbe8afd-bb73-44cd-a14d-0bb580befbad.png)
