### ISSUE TITLE
หน้าPreviewในGhost  มันใช้ไม่ได้น่ะคะ

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#155]
บทความสถานะเป็น Draft เมื่อกดPreview แล้วมันจะไม่มีอะไรเกิดขึ้นค่ะ
บทความสถานะ Public ไม่มีปุ่มให้กด Preview ค่ะ

- [x]  บทความสถานะDraft กด Preview แล้วต้องขึ้นหน้าจอให้ดู แบบเหมือนจริง
- [ ]  บทความสถานะ Public เวลาจะแก้ไขแล้วอยากดู Preview ต้องมี ปุ่มPreview

ปล. อันนี้แก้ยากง่ายยังไง ฝากบอกด้วยนะคับ

**Comment by thanakrit07** [comment]
@Phunut 
ข้อแรกของผมลอง test มันดูได้นะครับ
![Screen Shot 2564-11-25 at 17 15 28](https://user-images.githubusercontent.com/31263127/143422825-ca0c3012-f79a-45d1-8a08-f5bb3fc580b2.png)
ข้อที่สองตัว ghost ไม่มีมาให้อยู่แล้วอ่ะครับ น่าจะต้องเช็คให้แน่ใจก่อนกด publish จริงๆครับ

**Comment by Phunut** [comment]
@thanakrit07  อันนี้ข้อแรกดูได้ค่ะ. แต่ข้อ2 ดูไม่ได้อ่า

**Comment by Phunut** [comment]
@natnichamm   Devลองหาแก้แล้วแต่เหมือน ตัวghost cms  เหมือนจะไม่มีให้Previewได้.  
สรุป
- ถ้าสถานะDratt แก้ไขได้ ดูPreviewได้
- ถ้าสถานะpublished จะสามารถกลับมาแก้ไขอะไรได้ปกติ    แต่ จะไม่สามารถดูPreviewได้.
