### ISSUE TITLE
ชื่อ Public Tag ถ้ามีเว้นวรรค หน้าบ้านจะตกมาอีกบรรทัดนึง

### ISSUE THREAD

**Issue by natnichamm** [blockfint/blockfint-landing-2020#158]
หลังบ้าน
![image](https://user-images.githubusercontent.com/95010242/143384470-3d434f8c-f562-4507-86ed-2cdfb77e4b2c.png)

หน้าบ้าน
เป็นตรง Content Thumbnail ในหน้า Home, Blog, Tag, Contributor
![image](https://user-images.githubusercontent.com/95010242/143384593-a7c13c2a-8b9d-4025-9d4e-4afed7db1507.png)

![image](https://user-images.githubusercontent.com/95010242/143384656-f3b32690-fa96-4a31-bb99-061fd1452f0a.png)

**Comment by natnichamm** [comment]
ตอนนี้พี่แก้ขัดไปก่อนด้วยการเอาเว้นวรรคออก @thanakrit07

**Comment by thanakrit07** [comment]
https://blockfint-landing-2020-git-bugfix-fix-158-blockfint.vercel.app
