### ISSUE TITLE
ชื่อ Category มีขีดกลางมาจากไหนไม่รู้

### ISSUE THREAD

**Issue by natnichamm** [blockfint/blockfint-landing-2020#159]
หลังบ้าน
![image](https://user-images.githubusercontent.com/95010242/143385173-9d6fe9a3-8134-498f-81d3-52a670fd2e25.png)

หน้าบ้าน คือ ขีดกลางมาจากไหนไม่รู้อะ
![image](https://user-images.githubusercontent.com/95010242/143385130-7baca502-5e2b-47fb-90af-b0d1991435ec.png)

**Comment by thanakrit07** [comment]
![Screen Shot 2564-11-25 at 16 23 03](https://user-images.githubusercontent.com/31263127/143414619-82b2f191-7c6c-4b90-ae2c-ab3b6c020985.png)
@natnichamm 
ของผมมันขึ้นปกตินะครับ
