### ISSUE TITLE
บทความมีเส้นให้ scroll ซ้ายขวาได้ 

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#165]
บทความมีเส้น และสามารถ scroll ซ้ายขวาได้  

- [x] ต้องทำให้มันไม่มีเส้นค่ะ (อันนี้เปิดจาก iosค่ะ)

![image](https://user-images.githubusercontent.com/74232630/145754400-3d0a2250-5bcb-4b17-9f37-8af9d7e55400.png)

**Comment by thanakrit07** [comment]
น่าจะเป็นเส้นเพราะหน้าจอมันเลื่อนซ้ายขวาได้ ตอนนี้แก้ให้เลื่อนไม่ได้แล้วครับ ถ้าไม่ได้ซูมจอ
