### ISSUE TITLE
ชื่อตรง category  ตอนนี้มันดึงมาจาก slug ของ public tag ต้องให้มันมาจากชื่อ public tag

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#168]
- [x] ในหน้าBlogตรงcategory น่ะคะต้องทำให้คำตรงcategoty ถูกดึงมาจากชื่อ public tag ค่ะ   ตอนนี้มันดึงมาจาก slug ของ public tag 

ภาพแสดงตัวอย่างสิ่งที่ยังผิดอยู่ ตรงcategoryสังเกตตรงคำว่า "Unblock-design"นะคะ  ที่จริงแล้วมันควรดึงมาจาก public tag  ซึ่งควรจะเป็นคำว่า "Unblock Design" ไม่ใช่คำว่า"Unblock-design"ค่ะ
![image](https://user-images.githubusercontent.com/74232630/146757078-4dac21bb-57fd-4892-a355-f7fd964bc40d.png)
![image](https://user-images.githubusercontent.com/74232630/146757111-6f0e1f65-2afe-4e0b-8183-b3e819f0a36c.png)

**Comment by thanakrit07** [comment]
มีความจำเป็นจะต้องใช้ slug ในการเปลี่ยน page ครับ (URL ด้วย) แต่แก้ให้ขีดหายไปแล้วครับ เปลี่ยนขีดเป็น space

**Comment by Phunut** [comment]
@thanakrit07  แสดงว่าCategory ตรงนี้จะถูกเปลี่ยนไปตามชื่อSlug ใช่ไหมคะ
![image](https://user-images.githubusercontent.com/74232630/147460934-b0eee6f7-ca0e-4b14-99bc-bad5396465f9.png)
