### ISSUE TITLE
Mobile nav bar เปลี่ยนฟอนต์เป็น Prompt

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#26]
- [x]  Mobile nav bar เปลี่ยนฟอนต์เป็น Prompt จ้า

<img width="378" alt="Screen Shot 2564-04-21 at 10 01 23" src="https://user-images.githubusercontent.com/74232630/115490677-bcb28480-a288-11eb-9b12-02415efc2e51.png">

**Comment by jakapatb** [comment]
ผมลองดูมันก็เป็น prompt นะ
https://blockfint-landing-2020-gf4f0k7p4-blockfint.vercel.app/th

**Comment by Phunut** [comment]
ตอนนี้ถุกละ
