### ISSUE TITLE
Mainpage : ภาพแตก ขอชัดดีกว่านี้ได้ไหม

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#50]
Link:
https://blockfint-landing-2020-git-release-blockfint.vercel.app/th

ภาพมือถือแว่นขยายมันแตกปะคะ มีรูปคมๆกว่านี้ไหม?
![image](https://user-images.githubusercontent.com/82858380/118224434-5c8cb800-b4ad-11eb-9e47-ef2e40e8fc1f.png)

**Comment by Phunut** [comment]
### ภาพใหม่ค่ะ (อันเดียวกับที่แปะไปในLineกลุ่มทำเว็บ เมื่อวันศุกร์ค่ะ)
[https://drive.google.com/drive/folders/1pGeX7IxAx-9Ojrt0K13eEvPAjpMSYmBt?usp=sharing](url)
