### ISSUE TITLE
Footer : เว็บเรายังขาดหน้า นโยบายความเป็นส่วนตัวของ Blockfint ปะคะ

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#51]
จิ้มแล้วบ่ไปไหนเลยจ้า
![image](https://user-images.githubusercontent.com/82858380/118241981-ff056500-b4c6-11eb-86b4-deaffdd85758.png)

**Comment by jakapatb** [comment]
มันกดไม่ได้มาตั้งแต่อันเก่าแล้วครับ
แล้วเราไม่มีหน้านี้ด้วย

**Comment by momoparadise** [comment]
ช่ายๆ ละเราจะทำหน้านี้เพิ่มบ่ล่ะ?

**Comment by momoparadise** [comment]
DESIGN
zpl://project?pid=608b9cc33ee024309048d1da  
อันนี้หน้า Privacy & Policy นะคะ ตอนนี้ยังแต่ภาษาอังกฤษอย่างเดียว

TEXT
https://docs.google.com/document/d/1Y4rn6h6JsqQ_HbIthYyY69gWWCoRxI-QjCkM8LC4pHM/edit#

**Comment by amnuntita** [comment]
เปิด pull request แล้วค่ะ ชื่อ feature/policy
