### ISSUE TITLE
ส่วนสนใจธุรกิจ ขาตู้ไปรษณีย์ลอยจ้าา

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#52]
Link : https://blockfint-landing-2020-git-release-blockfint.vercel.app/th/about

ขาตู้ไรษณีย์ลอยจ้า เอามันลงมา (ไม่รีบๆ ว่างค่อยมาแก้) เป็น Desktop/Tablet จ้า
Mobile ไม่เป็นนะ
![image](https://user-images.githubusercontent.com/82858380/118260868-08013100-b4dd-11eb-9ec9-46d0937791ac.png)

**Comment by Phunut** [comment]
@jakapatb  ต้องให้เตรียมภาพใหม่ยังไงไหมคะ หรือตรงนี้เขียนCodeมันมันลงมาพอดีได้

**Comment by jakapatb** [comment]
เดะลองแก้เองก่อนครับ
