### ISSUE TITLE
Footer : สี icon ไม่เหมือนกัน ตั้งใจหรือเปล่า

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#53]
โทรศัพท์กะซองจดหมายคนละสี ฝากเช็คหน่อยจ้า ถ้าตั้งใจก็บ่ต้องแก้(แต่พี่ว่ามันแปลกๆ)
![image](https://user-images.githubusercontent.com/82858380/118261117-54e50780-b4dd-11eb-96f5-4a73e55e07eb.png)

**Comment by Phunut** [comment]
###ฝากเปลี่ยนเป็นสีดำ ตามBF website versionแรกค่ะ 
[zpl://screen?sid=5fa0573a9999fd31903c4bdc&pid=5f8d42f6c140c35b10d56a7c](url)
