### ISSUE TITLE
Work Details : Gideon ตรงส่วนบทสรุป Spacing มันแปลกๆ ฝากเช็คหน่อยค่ะ

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#56]
Link : https://blockfint-landing-2020-git-release-blockfint.vercel.app/th/products/gideon

Design มันวางระยะแปลกๆ รู้สึกดูละมันไม่ค่อยเรียบร้อยอะ
นัทช่วยเช็คหน่อยจ้า

![image](https://user-images.githubusercontent.com/82858380/118262377-033d7c80-b4df-11eb-8735-e5227ffcf88c.png)

**Comment by Phunut** [comment]
### ฝากปรับให้มันAlign บนเหมือนกันทั้งสองอันค่ะ 
[zpl://screen?pid=5f8d42f6c140c35b10d56a7c&sid=5f8e824956b080829c1593a5](url)
