### ISSUE TITLE
Padding ตรงหน้า Product Detailไม่เท่ากันค่ะ 

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#68]
**Problem**
Padding ตรง "บทสรุป"  ไม่เท่ากับ"ปัญหาในปัจจุบัน. (ในTablet)
![IMG_0080](https://user-images.githubusercontent.com/74232630/118753559-72282600-b88f-11eb-8526-5775ca0e40c5.PNG)

ต้องแก้เป็น Alignซ้ายกัน แบบนี้ค่ะ
![image](https://user-images.githubusercontent.com/74232630/118753769-de0a8e80-b88f-11eb-9fad-7936edf789fc.png)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ

**Comment by amnuntita** [comment]
แก้แล้วค่ะ

**Comment by jakapatb** [comment]
> แก้แล้วค่ะ

link ไป pull request ที่ทำด้วยครับ
