### ISSUE TITLE
ตรงNav barตัวหนังสือต้องเป็นSize 16 px เท่ากันหมดค่ะ

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#71]
### ตรงNav barตัวหนังสือต้องเป็นSize 16 px
**ตอนนี้คำว่า EN และ TH ฟอนท์ไซน์เหมือนจะเล็กกว่าตรงอื่นน่ะคะ**
![image](https://user-images.githubusercontent.com/74232630/118818688-cb6b7600-b8de-11eb-9a11-efdd05a63447.png)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ
