### ISSUE TITLE
ฟอนต์ ต้องเป็นขนาด 68px (ต้องใช้Fontเก่าของphase 1)

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#72]
### ฟอนต์ ต้องเป็นขนาด 68px (ต้องใช้Fontเก่าของphase 1 )
**หน้าHome ตรงtagline  Fontมันเปลี่ยนกลายเป็นฟอนต์เซตใหม่(ฟอนต์ของPhase 3). แต่ที่เราเคยคุยกันไว้  ตรงส่วนนนี้เราจะยึดฟอนต์เก่า ไม่เปลี่ยนไปใช้ฟอนต์แบบPhase 3 น่ะคะ.  ตอนนี้มันเลยดูบางเกินไปน่ะคะ **
![image](https://user-images.githubusercontent.com/74232630/118819355-7a0fb680-b8df-11eb-9ceb-d617f344462a.png)

ลิงค์ตัวอย่าง Font sizeที่ควรเป็น [https://www.blockfint.com/](url)
ลิงค์ฟอนต์ที่ดูบางเกินไป [https://dev-blockfint.vercel.app/](url)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ

**Comment by amnuntita** [comment]
แก้แล้วค่ะ
