### ISSUE TITLE
ขนาดwidthของรูปภาพเกินparagrahออกมาค่ะ จริงๆต้องเท่ากับwidth ของ paragraph

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#73]
**หน้า Blog detail รูปภาพตรง section นี้จะต้องมีขนาดกว้างเท่ากับwidth ของตัวหนังสือค่ะ**

ตัวอย่างที่ผิดอยู่
![image](https://user-images.githubusercontent.com/74232630/118839042-60c33600-b8f0-11eb-86ad-7b4d72ce2117.png)

ตัวอย่างที่ถูก
![image](https://user-images.githubusercontent.com/74232630/118842867-bf3de380-b8f3-11eb-8f5f-d63008f4d2e2.png)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ

**Comment by amnuntita** [comment]
แก้ใน ghost แล้วค่ะ
