### ISSUE TITLE
ตรงนี้Category กล่องสีเทา ไม่ต้องfixed widthค่ะ

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#74]
**ตรงนี้Category กล่องสีเทา ไม่ต้องfixed widthค่ะ   ให้มันHug contentไปเลย คอนเท้นยาว กล่องสีเทาก็จะยาว แต่ให้มีPadding 8 px ไว้เสมอ(ตามภาพค่ะ)**

ตัวอย่างที่อยากให้เป็น
![image](https://user-images.githubusercontent.com/74232630/118915160-a7e41200-b956-11eb-90ed-2ad5dc1d3321.png)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ
