### ISSUE TITLE
Phase 2ซ่อน Tagก่อนจ้า

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#75]
Phase 2 ตรงหน้าBlog detail ซ่อนTag  ก่อนได้เลยค่ะ

ตอนนี้ยังมีTagอยู่ ตามรูปด้านล่าง
![image](https://user-images.githubusercontent.com/74232630/118916418-19bd5b00-b959-11eb-8b4f-5f9ffbdaaf7a.png)

ดีไซน์ที่อยากให้เป็น คืออยากให้ซ่อนTagเอาไว้ก่อน (เพราะมันยังกดไม่ได้).   ตามรูปด้านล่างนี้
![image](https://user-images.githubusercontent.com/74232630/118916447-2e99ee80-b959-11eb-805d-8af537b16fe0.png)

**Comment by jakapatb** [comment]
@amnuntita  branch develop ครับ
