### ISSUE TITLE
Blog ใน Homepage ขึ้นไม่ครบ

### ISSUE THREAD

**Issue by jakapatb** [blockfint/blockfint-landing-2020#91]
![Screen Shot 2564-05-28 at 15 17 29](https://user-images.githubusercontent.com/38038597/119953111-dce00c80-bfc7-11eb-8057-9e88e30e4447.png)

จากที่ลองเป็นเพราะ get post limit  2 แล้วใน 2นั้นโดน filter ออก มันเลยเหลือ 0 หรือ 1

**Comment by justunee** [comment]
Fixed
