### ISSUE TITLE
แก้คำจากThinker Wise เป็นThinker LOS ค่ะ อัพเดทชีทให้แล้ว

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#94]

**Comment by momoparadise** [comment]
เหลือ 2 ที่ค่ะ
1. Homepage
https://blockfint-landing-2020-git-release-blockfint.vercel.app/th
![image](https://user-images.githubusercontent.com/82858380/120253086-a993cb00-c2b0-11eb-95f7-7fae0cbbe6b5.png)


2. Thinker LOS Page
https://blockfint-landing-2020-git-release-blockfint.vercel.app/th/products/thinker

![image](https://user-images.githubusercontent.com/82858380/120253054-8e28c000-c2b0-11eb-9437-002673357ed4.png)

**Comment by jakapatb** [comment]
https://dev-blockfint.vercel.app/works
