### ISSUE TITLE
สลับลำดับการแสดงผลค่ะ

### ISSUE THREAD

**Issue by momoparadise** [blockfint/blockfint-landing-2020#95]
ต้องแก้ 2 หน้านะคะ 
1. Home 
https://blockfint-landing-2020-git-release-blockfint.vercel.app/th

2. All works
https://blockfint-landing-2020-git-release-blockfint.vercel.app/th/works

**เรียงโปรเจ็คตามนี้นะคะ**
Thinker bank 
Thinker LOS 
Gideon 
Agritac

**Comment by jakapatb** [comment]
🤨
