### ISSUE TITLE
หน้าBlog detailเว้นบรรทัดไม่ได้

### ISSUE THREAD

**Issue by Phunut** [blockfint/blockfint-landing-2020#96]
### หน้าBlog Detail แต่ละparagraph มันไม่เว้นบรรทัดให้  ตอนนี้ทุกบรรทัดติดกันหมดเลย  (แต่ตอนสร้างบทความในGhost เรากดเว้นบรรทัดแล้วนะคะ)
อยากให้แต่ละบรรทัด ผู้เขียนบทความสามารถเลือกเว้นบรรทัดได้น่ะคะ

ภาพตัวอย่างในเว็บBlockfint
![image](https://user-images.githubusercontent.com/74232630/120163039-40b24180-c223-11eb-8d62-b014b042389f.png)

ภาพตัวอย่างการเว้นบรรทัดในGhost
![image](https://user-images.githubusercontent.com/74232630/120162899-12346680-c223-11eb-8db4-97443cda319a.png)

**Comment by jakapatb** [comment]
ตรงนี้ design ไม่มีรูปแบบ paragraph ต่อกันอะครับ เลยไม่รู้ว่าจะเว้นเท่าไหร่
ตอนนี้ผมใส่ margin bottom 24px ไว้ โอเคไหมครับ
